const tokens = [
  { type: "Identifier", value: "object" },
  { type: "equals", value: "=" },
  { type: "objectStart", value: "{" },
  { type: "Identifier", value: "name" },
  { type: "colon", value: ":" },
  { type: "StringLiteral", value: "hassan" },
  { type: "comma", value: "," },
  { type: "Identifier", value: "age" },
  { type: "colon", value: ":" },
  { type: "NumericLiteral", value: 21 },
  { type: "comma", value: "," },
  { type: "Identifier", value: "friends" },
  { type: "colon", value: ":" },
  { type: "NullLiteral", value: "null" },
  { type: "comma", value: "," },
  { type: "Identifier", value: "achievements" },
  { type: "colon", value: ":" },
  { type: "Identifier", value: "undefined" },
  { type: "comma", value: "," },
  { type: "Identifier", value: "hobbies" },
  { type: "colon", value: ":" },
  { type: "arrayStart", value: "[" },
  { type: "StringLiteral", value: "coding" },
  { type: "comma", value: "," },
  { type: "StringLiteral", value: "failing" },
  { type: "comma", value: "," },
  { type: "StringLiteral", value: "succeeding" },
  { type: "arrayEnd", value: "]" },
  { type: "comma", value: "," },
  { type: "Identifier", value: "address" },
  { type: "colon", value: ":" },
  { type: "objectStart", value: "{" },
  { type: "Identifier", value: "country" },
  { type: "colon", value: ":" },
  { type: "StringLiteral", value: "Pakistan" },
  { type: "comma", value: "," },
  { type: "Identifier", value: "city" },
  { type: "colon", value: ":" },
  { type: "StringLiteral", value: "Karachi" },
  { type: "objectEnd", value: "}" },
  { type: "comma", value: "," },
  { type: "NumericLiteral", value: 123 },
  { type: "colon", value: ":" },
  { type: "StringLiteral", value: "numbers" },
  { type: "comma", value: "," },
  { type: "Identifier", value: "cool" },
  { type: "colon", value: ":" },
  { type: "BooleanLiteral", value: false },
  { type: "objectEnd", value: "}" },
];



///////////////////////
